var h;h||=typeof Module != 'undefined' ? Module : {};var aa=[],ba="./this.program",ca="undefined"!=typeof document?document.currentScript?.src:void 0,da="",ea;try{da=(new URL(".",ca)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),k=console.error.bind(console),m,ha,p=!1,ia,q,r,ja,ka,u,v,w,la,x,y=0,ma=null;
function na(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);p=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var oa;async function pa(a){if(!m)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==oa&&m)a=new Uint8Array(m);else throw"both async and sync fetching of the wasm failed";return a}async function qa(a,b){try{var c=await pa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),na(d)}}
async function ra(a){var b=oa;if(!m&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return qa(b,a)}class sa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ta=a=>{for(;0<a.length;)a.shift()(h)},ua=[],va=[],wa=()=>{var a=h.preRun.shift();va.push(a)},xa=!0;function ya(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":q[a]=b;break;case "i8":q[a]=b;break;case "i16":ja[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":la[a>>3]=BigInt(b);break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":v[a>>2]=b;break;default:na(`invalid type for setValue: ${c}`)}}
var za="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&za)return za.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Aa=[0,31,60,91,121,152,182,213,244,274,305,335],Ba=[0,31,59,90,120,151,181,212,243,273,304,334],A=(a,b,c)=>{var d=r;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&
63}}d[b]=0;return b-e},Ca=a=>{if(!(a instanceof sa||"unwind"==a))throw a;},Da=a=>{ia=a;xa||(h.onExit?.(a),p=!0);throw new sa(a);},Ea=a=>{ia=a;Da(a)},Fa=()=>{if(!xa)try{var a=ia;ia=a;Da(a)}catch(b){Ca(b)}},Ga=!1,Ha=!1,Ia=[];
function Ja(){function a(){var c=h.canvas;Ha=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!Ka){Ka=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=
b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Ha&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var La=!1,Ma=void 0,C=void 0;
function Na(){if(!Ga)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Oa=[];function Pa(){var a=h.canvas;Oa.forEach(b=>b(a.width,a.height))}
function Qa(a,b,c){b&&c?(a.tf=b,a.lf=c):(b=a.tf,c=a.lf);var d=b,e=c;0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}C?(a.width!=d&&(a.width=
d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Ka,D=12288,Ra=!1,Sa=0,Ta=0,Ua=0,E={alpha:!1,depth:!1,stencil:!1,antialias:!1},Va={},Wa,F,Xa=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Ya=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Za=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},$a=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},ab=1,bb=[],G=[],cb=[],H=[],J=[],K=[],db=[],M=[],N=[],eb={},fb=4,gb=0,hb=a=>{for(var b=ab++,c=a.length;c<b;c++)a[c]=null;return b},ib=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=F[c](),g=f&&hb(d);f?(f.name=g,d[g]=f):O||=1282;u[b+4*e>>2]=g}},kb=(a,b)=>{a.oe||(a.oe=a.getContext,a.getContext=function(d,e){e=a.oe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?jb(c,b):0},jb=(a,b)=>{var c=
hb(M),d={handle:c,attributes:b,version:b.Ve,je:a};a.canvas&&(a.canvas.ne=d);M[c]=d;("undefined"==typeof b.gf||b.gf)&&lb(d);return c},nb=a=>{mb=M[a];h.ctx=F=mb?.je},lb=a=>{a||=mb;if(!a.nf){a.nf=!0;var b=a.je;b.Ff=b.getExtension("WEBGL_multi_draw");b.jf=b.getExtension("EXT_polygon_offset_clamp");b.hf=b.getExtension("EXT_clip_control");b.sf=b.getExtension("WEBGL_polygon_mode");Xa(b);Ya(b);Za(b);b.ie=b.getExtension("EXT_disjoint_timer_query");$a(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},ob={},O,mb,pb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Q=a=>{var b=pb(a)+1,c=P(b);c&&A(a,c,b);return c},Fb=(a,b,c,d,e)=>{function f(){return g<qb?(Fa(),!1):!0}rb=a;sb=d;var g=qb;tb=!1;ub=function(){if(!p)if(0<vb.length){var l=vb.shift();l.Bf(l.uf);if(wb){var n=wb,t=0==n%1?n-1:Math.floor(n);wb=l.xf?t:(8*n+(t+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=wb??0,t=xb.Af??0,n?n<t?h.setStatus("{message} ({expected - remaining}/{expected})"):
h.setStatus(l):h.setStatus(""));f()&&setTimeout(ub,0)}else if(f())if(yb=yb+1|0,1==zb&&1<Ab&&0!=yb%Ab)R();else{0==zb&&(Bb=performance.now());a:if(!p){for(l of Cb)if(!1===l())break a;if(!p)try{a(),Fa()}catch(B){Ca(B)}for(n of Db)n()}f()&&R()}};e||(0<b?Eb(0,1E3/b):Eb(1,1),R());if(c)throw"unwind";},tb=!1,R=null,qb=0,rb=null,sb=0,zb=0,Ab=0,yb=0,vb=[],Cb=[],Db=[],Gb=0;
function Hb(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Gb)Gb=b+1E3/60;else for(;b+2>=Gb;)Gb+=1E3/60;setTimeout(a,Math.max(Gb-b,0))}}
var xb={},ub,wb,Bb,Ib,Eb=(a,b)=>{zb=a;Ab=b;if(rb)if(tb||=!0,0==a)R=function(){setTimeout(ub,Math.max(0,Bb+b-performance.now())|0)};else if(1==a)R=function(){Hb(ub)};else if(2==a){if("undefined"==typeof Ib)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ib=d=>{c.push(d);postMessage("setimmediate","*")}}else Ib=setImmediate;R=function(){Ib(ub)}}},Jb=[],Kb=(a,b)=>{Jb.length=0;
for(var c;c=r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Jb.push(112==c?v[b>>2]:106==c?la[b>>3]:105==c?u[b>>2]:x[b>>3]);b+=d?8:4}return Jb};function Lb(a){var b=S.ee[a];b.target.removeEventListener(b.be,b.Te,b.ce);S.ee.splice(a,1)}function Mb(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of S.ke)if(e.Je==a&&d(e.Pe,c))return;S.ke.push({Je:a,Xe:b,Pe:c});S.ke.sort((f,g)=>f.Xe<g.Xe)}function Nb(a){S.ke=S.ke.filter(b=>b.Je!=a)}
function Ob(){return navigator.userActivation?navigator.userActivation.isActive:S.Ee&&S.af.qe}function Pb(){if(Ob()){var a=S.ke;S.ke=[];for(var b of a)b.Je(...b.Pe)}}function T(a){if(!a.target)return-4;if(a.de)a.Te=function(c){++S.Ee;S.af=a;Pb();a.fe(c);Pb();--S.Ee},a.target.addEventListener(a.be,a.Te,a.ce),S.ee.push(a);else for(var b=0;b<S.ee.length;++b)S.ee[b].target==a.target&&S.ee[b].be==a.be&&Lb(b--);return 0}
function Qb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var S={vf:0,De:0,Fe:0,ye:0,Oe:0,Le:0,Be:0,zf:0,Gf:0,yf:0,Ce:0,He:0,Ne:0,Ke:0,Df(a,b,c){q.set(q.subarray(b,b+c),a)},Hf(){for(;S.ee.length;)Lb(S.ee.length-1);S.ke=[]},Ee:0,ke:[],ee:[],qf:(a,b)=>{for(var c=0;c<S.ee.length;++c)S.ee[c].target!=a||b&&b!=S.ee[c].be||Lb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Rb=[0,document,window],U=a=>{a=2<a?a?z(r,a):"":a;return Rb[a]||document.querySelector(a)},Tb=a=>{var b=pb(a)+1,c=Sb(b);A(a,c,b);return c},Wb=a=>
{var b=Ub(),c=Sb(8),d=c+4;a=Tb(a.id);if(a=U(a))u[c>>2]=a.width,u[d>>2]=a.height;c=[u[c>>2],u[d>>2]];Vb(b);return c},Xb=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},Yb=(a,b,c)=>{if(a.wf){var d=Ub();a=Tb(a.id);Xb(a,b,c);Vb(d)}else a.width=b,a.height=c},Zb={},$b=[],ac,V=a=>{var b=$b[a];b||($b[a]=b=ac.get(a));return b},bc=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",
b),Yb(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=t,a.style.paddingRight=B,a.style.paddingTop=L,a.style.paddingBottom=I,a.style.marginLeft=ed,a.style.marginRight=fd,a.style.marginTop=gd,a.style.marginBottom=hd,document.body.style.margin=jd,document.documentElement.style.overflow=kd,document.body.scroll=ld,a.style.le=md,a.ne&&a.ne.je.viewport(0,0,d,e),Zb.re&&V(Zb.re)(37,
0,Zb.Re))}var c=Wb(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,t=a.style.paddingLeft,B=a.style.paddingRight,L=a.style.paddingTop,I=a.style.paddingBottom,ed=a.style.marginLeft,fd=a.style.marginRight,gd=a.style.marginTop,hd=a.style.marginBottom,jd=document.body.style.margin,kd=document.documentElement.style.overflow,ld=document.body.scroll,md=a.style.le;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",
b)},cc=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},dc=a=>0>Rb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},ec=(a,b)=>{if(0!=b.Ie||0!=b.ze){bc(a);var c=b.rf?innerWidth:screen.width,d=b.rf?innerHeight:screen.height,e=dc(a),f=e.width;e=e.height;var g=Wb(a),l=g[0];g=g[1];3==b.Ie?(cc(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Ie&&(c*g<l*d?(f=g*c/l,cc(a,(d-f)/2,0),d=f):(f=l*d/g,cc(a,0,(c-f)/2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor=
"black");let t;(t=document.body.style).backgroundColor||(t.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.kf&&(a.style.le="optimizeSpeed",a.style.le="-moz-crisp-edges",a.style.le="-o-crisp-edges",a.style.le="-webkit-optimize-contrast",a.style.le="optimize-contrast",a.style.le="crisp-edges",a.style.le="pixelated");n=2==b.ze?devicePixelRatio:1;0!=b.ze&&(c=c*n|0,d=d*n|0,Yb(a,c,d),a.ne&&a.ne.je.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return S.fullscreenEnabled()?-3:-1;Zb=b;b.re&&V(b.re)(37,0,b.Re);return 0},fc=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},gc=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)q[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
q[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;A(b.id,a+1112,64);A(b.mapping,a+1176,64)},hc=a=>{var b=document.pointerLockElement||document.oe||document.Se||document.Qe;q[a]=!!b;var c=b?.id||"";A(Qb(b),a+1,128);A(c,a+129,128)},ic=(a,b)=>{F.attachShader(G[a],K[b])},jc=(a,b)=>{F.bindBuffer(a,bb[b])},kc=(a,b)=>F.blendFunc(a,b),lc=(a,b,c,d)=>{F.bufferData(a,c?r.subarray(c,c+b):b,d)},mc=a=>F.clear(a),nc=(a,b,c,d)=>F.clearColor(a,b,c,d),oc=a=>{F.compileShader(K[a])},
pc=()=>{var a=hb(G),b=F.createProgram();b.name=a;b.xe=b.ve=b.we=0;b.Me=1;G[a]=b;return a},qc=a=>{var b=hb(K);K[b]=F.createShader(a);return b},rc=a=>F.disable(a),sc=[],tc=(a,b,c,d)=>{F.drawElements(a,b,c,d)},uc=a=>F.enable(a),vc=a=>{F.enableVertexAttribArray(a)},wc=(a,b)=>{ib(a,b,"createBuffer",bb)},xc=(a,b,c,d,e,f,g,l)=>{b=G[b];if(a=F[a](b,c))d=l&&A(a.name,l,d),e&&(u[e>>2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)},yc=(a,b)=>F.getAttribLocation(G[a],b?z(r,b):""),zc=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=
1;break;case 36344:0!=c&&1!=c&&(O||=1280);return;case 36345:d=0;break;case 34466:var e=F.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=F.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":O||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:O||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||
e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:q[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){O||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:O||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;v[b>>2]=c;v[b+4>>2]=(c-v[b>>2])/4294967296;break;
case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:q[b]=d?1:0}}else O||=1281},Ac=(a,b,c)=>{if(c){a=F.ie.getQueryObjectEXT(N[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d;v[c+4>>2]=(d-v[c>>2])/4294967296}else O||=1281},Bc=(a,b,c)=>{if(c){a=F.ie.getQueryObjectEXT(N[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else O||=1281},Cc=()=>{var a=$a(F);return a=a.concat(a.map(b=>"GL_"+b))},Dc=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ec=a=>{var b=a.pe,c=a.Ze,d;if(!b){a.pe=b={};a.Ye={};var e=
F.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=F.getActiveUniform(a,d);var g=f.name;f=f.size;var l=Dc(g);l=0<l?g.slice(0,l):g;var n=a.Me;a.Me+=f;c[l]=[f,n];for(g=0;g<f;++g)b[n]=g,a.Ye[n++]=l}}},Fc=(a,b)=>{b=b?z(r,b):"";if(a=G[a]){Ec(a);var c=a.pe,d=0,e=b,f=Dc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Ze[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||F.getUniformLocation(a,b)))return d}else O||=1281;return-1},W=a=>{var b=F.bf;if(b){var c=b.pe[a];"number"==typeof c&&(b.pe[a]=c=F.getUniformLocation(b,
b.Ye[a]+(0<c?`[${c}]`:"")));return c}O||=1282},Gc=(a,b,c,d)=>{if(c)if(a=G[a],Ec(a),a=F.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else O||=1281},Hc=(a,b,c,d)=>{if(c)if(a=F.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=
0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else O||=1281},Ic=a=>{a=G[a];F.linkProgram(a);a.pe=0;a.Ze={}},Jc=(a,b,c,d,e)=>{a-=5120;a=1==a?r:4==a?u:6==a?w:5==a||28922==a?v:ka;b=d*((gb||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+fb-1&-fb);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Kc=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=v[c+4*f>>2])?
z(r,g,d?v[d+4*f>>2]:void 0):"";e+=g}F.shaderSource(K[a],e)},Lc=(a,b)=>{F.uniform1f(W(a),b)},X=[],Mc=[],Nc=(a,b,c,d)=>{if(18>=b){var e=X[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);F.uniformMatrix4fv(W(a),!!c,e)},Oc=a=>{a=G[a];
F.useProgram(a);F.bf=a},Pc=(a,b,c,d,e,f)=>{F.vertexAttribPointer(a,b,c,!!d,e,f)},Qc=(a,b,c,d)=>F.viewport(a,b,c,d),Rc=(a,b)=>{if(!S.fullscreenEnabled())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Ob()?ec(a,b):b.ff?(Mb(ec,1,[a,b]),1):-2:-3:-4},Sc=()=>{try{if(navigator.getGamepads)return(S.ue=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Tc=(a,b)=>{var c={target:U(2),be:"beforeunload",de:b,fe:(d=event)=>{var e=V(b)(28,0,a);e&&=e?z(r,e):"";if(e)return d.preventDefault(),
d.returnValue=e},ce:!0};return T(c)},Uc=(a,b,c,d,e,f)=>{S.Be||(S.Be=P(256));a={target:U(a),be:f,de:d,fe:(g=event)=>{var l=g.target.id?g.target.id:"",n=S.Be;A(Qb(g.target),n+0,128);A(l,n+128,128);V(d)(e,n,b)&&g.preventDefault()},ce:c};return T(a)},Vc=(a,b,c,d,e)=>{S.Ce||(S.Ce=P(276));return T({target:a,be:e,de:d,fe:(f=event)=>{var g=S.Ce,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;q[g]=n;q[g+1]=S.fullscreenEnabled();
var t=n?l:S.pf,B=t?.id||"";A(Qb(t),g+2,128);A(B,g+130,128);u[g+260>>2]=t?t.clientWidth:0;u[g+264>>2]=t?t.clientHeight:0;u[g+268>>2]=screen.width;u[g+272>>2]=screen.height;n&&(S.pf=l);V(d)(19,g,b)&&f.preventDefault()},ce:c})},Wc=(a,b,c,d,e)=>{S.De||(S.De=P(1240));b={target:U(2),qe:!0,be:e,de:c,fe:(f=event)=>{var g=S.De;gc(g,f.gamepad);V(c)(d,g,a)&&f.preventDefault()},ce:b};return T(b)},Xc=(a,b,c,d,e,f)=>{S.Fe||(S.Fe=P(160));a={target:U(a),be:f,de:d,fe:g=>{var l=S.Fe;x[l>>3]=g.timeStamp;var n=l>>2;
u[n+2]=g.location;q[l+12]=g.ctrlKey;q[l+13]=g.shiftKey;q[l+14]=g.altKey;q[l+15]=g.metaKey;q[l+16]=g.repeat;u[n+5]=g.charCode;u[n+6]=g.keyCode;u[n+7]=g.which;A(g.key||"",l+32,32);A(g.code||"",l+64,32);A(g.char||"",l+96,32);A(g.locale||"",l+128,32);V(d)(e,l,b)&&g.preventDefault()},ce:c};return T(a)},Yc=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;ja[2*d+14]=b.button;
ja[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=dc(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},Zc=(a,b,c,d,e,f)=>{S.ye||(S.ye=P(64));a=U(a);return T({target:a,qe:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,be:f,de:d,fe:(g=event)=>{Yc(S.ye,g,a);V(d)(e,S.ye,b)&&g.preventDefault()},ce:c})},$c=(a,b,c,d,e)=>{S.He||(S.He=P(257));return T({target:a,be:e,de:d,fe:(f=event)=>{var g=S.He;hc(g);V(d)(20,g,b)&&f.preventDefault()},ce:c})},ad=(a,b,c,d)=>{S.Le||(S.Le=P(36));a=U(a);
return T({target:a,be:"resize",de:d,fe:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=S.Le;u[g>>2]=0;u[g+4>>2]=f.clientWidth;u[g+8>>2]=f.clientHeight;u[g+12>>2]=innerWidth;u[g+16>>2]=innerHeight;u[g+20>>2]=outerWidth;u[g+24>>2]=outerHeight;u[g+28>>2]=pageXOffset|0;u[g+32>>2]=pageYOffset|0;V(d)(10,g,b)&&e.preventDefault()}}},ce:c})},bd=(a,b,c,d,e,f)=>{S.Ke||(S.Ke=P(1552));a=U(a);return T({target:a,qe:"touchstart"==f||"touchend"==f,be:f,de:d,fe:g=>{var l={},n=g.touches;for(var t of n)t.Ue=
t.We=0,l[t.identifier]=t;for(var B of g.changedTouches)B.Ue=1,l[B.identifier]=B;for(var L of g.targetTouches)l[L.identifier].We=1;n=S.Ke;x[n>>3]=g.timeStamp;q[n+12]=g.ctrlKey;q[n+13]=g.shiftKey;q[n+14]=g.altKey;q[n+15]=g.metaKey;t=n+16;B=dc(a);L=0;for(let I of Object.values(l))if(l=t>>2,u[l]=I.identifier,u[l+1]=I.screenX,u[l+2]=I.screenY,u[l+3]=I.clientX,u[l+4]=I.clientY,u[l+5]=I.pageX,u[l+6]=I.pageY,q[t+28]=I.Ue,q[t+29]=I.We,u[l+8]=I.clientX-(B.left|0),u[l+9]=I.clientY-(B.top|0),t+=48,31<++L)break;
u[n+8>>2]=L;V(d)(e,n,b)&&g.preventDefault()},ce:c})},cd=(a,b,c)=>{var d=Rb[1];S.Ne||(S.Ne=P(8));return T({target:d,be:"visibilitychange",de:c,fe:(e=event)=>{var f=S.Ne,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);q[f]=document.hidden;u[f+4>>2]=g;V(c)(21,f,a)&&e.preventDefault()},ce:b})},dd=(a,b,c,d)=>{S.Oe||(S.Oe=P(96));return T({target:a,qe:!0,be:"wheel",de:d,fe:(e=event)=>{var f=S.Oe;Yc(f,e,a);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;u[f+88>>
2]=e.deltaMode;V(d)(9,f,b)&&e.preventDefault()},ce:c})},nd={},pd=()=>{if(!od){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in nd)void 0===nd[b]?delete a[b]:a[b]=nd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);od=c}return od},od,qd=[null,[],[]],rd=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},sd=a=>{var b;b||=[document,document.getElementById("canvas")];
["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&rd(d,c,()=>{"suspended"===a.state&&a.resume()})})})},td=(a,b=[])=>{V(a)(...b)};
h.requestFullscreen=function(a,b){function c(){Ga=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Na,Ma&&d.requestPointerLock(),Ga=!0,C?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>2]|8388608),Qa(h.canvas),Pa()):Qa(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),C?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>
2]&-8388609),Qa(h.canvas),Pa()):Qa(d));h.onFullScreen?.(Ga);h.onFullscreen?.(Ga)}Ma=a;C=b;"undefined"==typeof Ma&&(Ma=!0);"undefined"==typeof C&&(C=!1);var d=h.canvas;La||(La=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||
e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){Qa(h.canvas,a,b);c||Pa()};h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var f={antialias:!1,alpha:!1,Ve:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof ob&&(e=kb(a,f)))var l=M[e].je}else l=a.getContext("2d");if(!l)return null;c&&(h.ctx=l,b&&nb(e),Ia.forEach(n=>n()),Ja());return l};h.requestAnimationFrame=Hb;h.pauseMainLoop=function(){R=null;qb++};h.resumeMainLoop=function(){qb++;var a=zb,b=Ab,c=rb;rb=null;Fb(c,0,!1,sb,!0);Eb(a,b);R()};h.preMainLoop&&Cb.push(h.preMainLoop);
h.postMainLoop&&Db.push(h.postMainLoop);for(let a=0;32>a;++a)sc.push(Array(a));for(var ud=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=ud.subarray(0,Y);var vd=new Int32Array(288);for(Y=0;288>=Y;++Y)Mc[Y]=vd.subarray(0,Y);h.noExitRuntime&&(xa=h.noExitRuntime);h.print&&(fa=h.print);h.printErr&&(k=h.printErr);h.wasmBinary&&(m=h.wasmBinary);h.arguments&&(aa=h.arguments);h.thisProgram&&(ba=h.thisProgram);
var wd={20591965:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,20592112:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,20592346:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.ae||("undefined"!==typeof AudioContext?b.ae=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ae=new webkitAudioContext),
b.ae&&"undefined"===typeof navigator.userActivation&&sd(b.ae));return void 0===b.ae?-1:0},20592898:()=>h.SDL2.ae.sampleRate,20592966:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.capture.he&&(clearInterval(g.capture.he),g.capture.he=void 0,g.capture.me=void 0);g.capture.Ge=g.ae.createMediaStreamSource(l);g.capture.ge=g.ae.createScriptProcessor(b,a,1);g.capture.ge.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Ae=n.inputBuffer,td(c,
[d]))};g.capture.Ge.connect(g.capture.ge);g.capture.ge.connect(g.ae.destination);g.capture.stream=l}var g=h.SDL2;g.capture.me=g.ae.createBuffer(a,b,g.ae.sampleRate);g.capture.me.getChannelData(0).fill(0);g.capture.he=setInterval(function(){g.capture.Ae=g.capture.me;td(c,[d])},b/g.ae.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,
video:!1},f,e)},20594659:(a,b,c,d)=>{var e=h.SDL2;e.audio.ge=e.ae.createScriptProcessor(b,0,a);e.audio.ge.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.he&&(clearInterval(e.audio.he),e.audio.he=void 0,e.audio.me=void 0),e.audio.te=f.outputBuffer,td(c,[d]))};e.audio.ge.connect(e.ae.destination);"suspended"===e.ae.state&&(e.audio.me=e.ae.createBuffer(a,b,e.ae.sampleRate),e.audio.me.getChannelData(0).fill(0),e.audio.he=setInterval(function(){"undefined"!==typeof navigator.userActivation&&
navigator.userActivation.hasBeenActive&&e.ae.resume();e.audio.te=e.audio.me;td(c,[d]);e.audio.te=void 0},b/e.ae.sampleRate*1E3))},20595834:(a,b)=>{for(var c=h.SDL2,d=c.capture.Ae.numberOfChannels,e=0;e<d;++e){var f=c.capture.Ae.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)ya(a+4*g,f[g]);else for(g=0;g<b;++g)ya(a+4*(g*d+e),f[g])}},20596439:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=
c.audio.te.numberOfChannels,e=0;e<d;++e){var f=c.audio.te.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=w[a+(g*d+e)]}},20596928:a=>{var b=h.SDL2;if(a){void 0!==b.capture.he&&clearInterval(b.capture.he);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.ge&&(b.capture.ge.onaudioprocess=
function(){},b.capture.ge.disconnect());void 0!==b.capture.Ge&&b.capture.Ge.disconnect();b.capture=void 0}else void 0!=b.audio.ge&&b.audio.ge.disconnect(),void 0!==b.audio.he&&clearInterval(b.audio.he),b.audio=void 0;void 0!==b.ae&&void 0===b.audio&&void 0===b.capture&&(b.ae.close(),b.ae=void 0)},20597934:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.$e!==h.canvas&&(d.se=h.createContext(h.canvas,!1,!0),d.$e=h.canvas);if(d.w!==a||d.h!==b||d.mf!==d.se)d.image=d.se.createImageData(a,b),d.w=a,d.h=b,d.mf=
d.se;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.df!==a&&(d.cf=new Int32Array(a.buffer),d.ef=new Uint8Array(a.buffer),d.df=a),a=d.cf,c=a.length,a.set(u.subarray(b,b+c)),a=d.ef,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|
0;else for(;b<e;)a[b]=255,b=b+4|0;d.se.putImageData(d.image,0,0)},20599402:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<n;){var t=u[e];b[l]=t&255;b[l+1]=t>>8&255;b[l+2]=t>>16&255;b[l+3]=t>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?
"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=P(c.length+1);A(c,d,c.length+1);return d},20600390:a=>{h.canvas&&(h.canvas.style.cursor=a?z(r,a):"")},20600473:()=>{h.canvas&&(h.canvas.style.cursor="none")},20600542:()=>window.innerWidth,20600572:()=>window.innerHeight},xd={$:function(){return 0},ab:function(){return 0},bb:function(){},Ua:()=>{},Wa:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);u[b>>2]=a.getSeconds();u[b+4>>2]=a.getMinutes();
u[b+8>>2]=a.getHours();u[b+12>>2]=a.getDate();u[b+16>>2]=a.getMonth();u[b+20>>2]=a.getFullYear()-1900;u[b+24>>2]=a.getDay();var c=a.getFullYear();u[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Ba:Aa)[a.getMonth()]+a.getDate()-1|0;u[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();u[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},Xa:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();
e=(new Date(e,6,1)).getTimezoneOffset();v[a>>2]=60*Math.max(f,e);u[b>>2]=Number(f!=e);b=g=>{var l=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(A(a,c,17),A(b,d,17)):(A(a,d,17),A(b,c,17))},Ka:a=>{if(12448==a)return D=12288,1;D=12300;return 0},Na:(a,b,c,d,e)=>{if(62E3!=a)D=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)E.alpha=0<u[b+4>>2];else if(12325==a)E.depth=0<u[b+4>>2];else if(12326==a)E.stencil=0<u[b+4>>
2];else if(12337==a)a=u[b+4>>2],E.antialias=0<a;else if(12338==a)a=u[b+4>>2],E.antialias=1==a;else if(12544==a)E.Cf=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(v[c>>2]=62002),D=12288,c=1):(D=12300,c=0)}return c},Ba:(a,b,c,d)=>{if(62E3!=a)return D=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return D=12292,0;d+=8}if(2!=a)return D=12293,0;E.Ve=a-1;E.Ef=0;Wa=kb(h.canvas,E);if(0!=Wa)return D=12288,nb(Wa),Ia.forEach(e=>e()),nb(null),
62004;D=12297;return 0},Da:(a,b)=>{if(62E3!=a)return D=12296,0;if(62002!=b)return D=12293,0;D=12288;return 62006},Ca:(a,b)=>{if(62E3!=a)return D=12296,0;if(62004!=b)return D=12294,0;a=Wa;mb===M[a]&&(mb=null);"object"==typeof S&&S.qf(M[a].je.canvas);M[a]?.je.canvas&&(M[a].je.canvas.ne=void 0);M[a]=null;D=12288;Sa==b&&(Sa=0);return 1},Ea:(a,b)=>{if(62E3!=a)return D=12296,0;if(62006!=b)return D=12301,1;Ta==b&&(Ta=0);Ua==b&&(Ua=0);D=12288;return 1},Oa:(a,b,c,d)=>{if(62E3!=a)return D=12296,0;if(62002!=
b)return D=12293,0;if(!d)return D=12300,0;D=12288;switch(c){case 12320:return u[d>>2]=E.alpha?32:24,1;case 12321:return u[d>>2]=E.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=E.depth?24:0,1;case 12326:return u[d>>2]=E.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>
2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=E.antialias?4:0,1;case 12338:return u[d>>2]=E.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>
2]=4,1;case 12354:return u[d>>2]=0,1;default:return D=12292,0}},T:a=>{D=12288;return 0!=a&&1!=a?0:62E3},Aa:()=>D,La:(a,b,c)=>{if(62E3!=a)return D=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);Ra=!0;D=12288;return 1},Fa:(a,b,c,d)=>{if(62E3!=a)return D=12296,0;if(0!=d&&62004!=d)return D=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return D=12301,0;nb(d?Wa:null);Sa=d;Ua=b;Ta=c;D=12288;return 1},za:(a,b)=>{if(62E3!=a)return D=12296,0;D=12288;if(Va[b])return Va[b];switch(b){case 12371:a=Q("Emscripten");break;case 12372:a=
Q("1.4 Emscripten EGL");break;case 12373:a=Q("");break;case 12429:a=Q("OpenGL_ES");break;default:return D=12300,0}return Va[b]=a},Ga:()=>{if(Ra)if(F)if(F.isContextLost())D=12302;else return D=12288,1;else D=12290;else D=12289;return 0},Ha:(a,b)=>{if(62E3!=a)return D=12296,0;0==b?Eb(0,0):Eb(1,b);D=12288;return 1},Ma:a=>{if(62E3!=a)return D=12296,0;Ua=Ta=Sa=0;Ra=!1;D=12288;return 1},Ja:()=>{D=12288;return 1},Ia:()=>{D=12288;return 1},Qa:(a,b,c)=>{b=Kb(b,c);return wd[a](...b)},e:(a,b,c)=>{b=Kb(b,c);
return wd[a](...b)},Ra:(a,b,c)=>{b=Kb(b,c);return wd[a](...b)},aa:()=>Date.now(),ua:()=>{if(!S.fullscreenEnabled())return-1;Nb(ec);var a=Rb[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},xa:()=>{Nb(fc);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},m:()=>devicePixelRatio,g:(a,b,c)=>{a=U(a);if(!a)return-4;a=dc(a);x[b>>3]=a.width;x[c>>3]=a.height;
return 0},W:(a,b)=>{if(0>a||a>=S.ue.length)return-5;if(!S.ue[a])return-7;gc(b,S.ue[a]);return 0},Y:()=>performance.now(),Pa:()=>S.ue.length,gc:a=>{a&&hc(a);return document.body&&(document.body.requestPointerLock||document.body.oe||document.body.Se||document.body.Qe)?0:-1},ya:(a,b)=>{u[a>>2]=screen.width;u[b>>2]=screen.height},Rd:a=>F.activeTexture(a),Qd:ic,qa:(a,b)=>{F.ie.beginQueryEXT(a,N[b])},Pd:(a,b,c)=>{F.bindAttribLocation(G[a],b,c?z(r,c):"")},Od:jc,Nd:(a,b)=>{F.bindFramebuffer(a,cb[b])},Md:(a,
b)=>{F.bindRenderbuffer(a,H[b])},Ld:(a,b)=>{F.bindTexture(a,J[b])},ha:a=>{F.bindVertexArray(db[a])},Kd:(a,b,c,d)=>F.blendColor(a,b,c,d),Id:a=>F.blendEquation(a),Hd:(a,b)=>F.blendEquationSeparate(a,b),Gd:kc,Fd:(a,b,c,d)=>F.blendFuncSeparate(a,b,c,d),Ed:lc,Dd:(a,b,c,d)=>{F.bufferSubData(a,b,r.subarray(d,d+c))},Cd:a=>F.checkFramebufferStatus(a),Bd:mc,Ad:nc,zd:a=>F.clearDepth(a),yd:a=>F.clearStencil(a),db:(a,b)=>{F.hf.clipControlEXT(a,b)},xd:(a,b,c,d)=>{F.colorMask(!!a,!!b,!!c,!!d)},wd:oc,vd:(a,b,c,d,
e,f,g,l)=>{F.compressedTexImage2D(a,b,c,d,e,f,r.subarray(l,l+g))},ud:(a,b,c,d,e,f,g,l,n)=>{F.compressedTexSubImage2D(a,b,c,d,e,f,g,r.subarray(n,n+l))},td:(a,b,c,d,e,f,g,l)=>F.copyTexImage2D(a,b,c,d,e,f,g,l),sd:(a,b,c,d,e,f,g,l)=>F.copyTexSubImage2D(a,b,c,d,e,f,g,l),rd:pc,qd:qc,pd:a=>F.cullFace(a),od:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=bb[d];e&&(F.deleteBuffer(e),e.name=0,bb[d]=null)}},nd:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=cb[d];e&&(F.deleteFramebuffer(e),e.name=0,cb[d]=
null)}},md:a=>{if(a){var b=G[a];b?(F.deleteProgram(b),b.name=0,G[a]=null):O||=1281}},sa:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=N[d];e&&(F.ie.deleteQueryEXT(e),N[d]=null)}},ld:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=H[d];e&&(F.deleteRenderbuffer(e),e.name=0,H[d]=null)}},kd:a=>{if(a){var b=K[a];b?(F.deleteShader(b),K[a]=null):O||=1281}},jd:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=J[d];e&&(F.deleteTexture(e),e.name=0,J[d]=null)}},ga:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*
c>>2];F.deleteVertexArray(db[d]);db[d]=null}},id:a=>F.depthFunc(a),hd:a=>{F.depthMask(!!a)},gd:(a,b)=>F.depthRange(a,b),fd:(a,b)=>{F.detachShader(G[a],K[b])},dd:rc,cd:a=>{F.disableVertexAttribArray(a)},bd:(a,b,c)=>{F.drawArrays(a,b,c)},ca:(a,b,c,d)=>{F.drawArraysInstanced(a,b,c,d)},da:(a,b)=>{for(var c=sc[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];F.drawBuffers(c)},ad:tc,Td:(a,b,c,d,e)=>{F.drawElementsInstanced(a,b,c,d,e)},$c:uc,_c:vc,pa:a=>{F.ie.endQueryEXT(a)},Zc:()=>F.finish(),Yc:()=>F.flush(),Xc:(a,b,c,
d)=>{F.framebufferRenderbuffer(a,b,c,H[d])},Wc:(a,b,c,d,e)=>{F.framebufferTexture2D(a,b,c,J[d],e)},Vc:a=>F.frontFace(a),Uc:wc,Sc:(a,b)=>{ib(a,b,"createFramebuffer",cb)},ta:(a,b)=>{for(var c=0;c<a;c++){var d=F.ie.createQueryEXT();if(!d){for(O||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=hb(N);d.name=e;N[e]=d;u[b+4*c>>2]=e}},Rc:(a,b)=>{ib(a,b,"createRenderbuffer",H)},Qc:(a,b)=>{ib(a,b,"createTexture",J)},fa:(a,b)=>{ib(a,b,"createVertexArray",db)},Tc:a=>F.generateMipmap(a),Pc:(a,b,c,d,e,f,g)=>xc("getActiveAttrib",
a,b,c,d,e,f,g),Oc:(a,b,c,d,e,f,g)=>xc("getActiveUniform",a,b,c,d,e,f,g),Nc:(a,b,c,d)=>{a=F.getAttachedShaders(G[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=K.indexOf(a[b])},Mc:yc,Lc:(a,b)=>zc(a,b,4),Kc:(a,b,c)=>{c?u[c>>2]=F.getBufferParameter(a,b):O||=1281},Jc:()=>{var a=F.getError()||O;O=0;return a},Ic:(a,b)=>zc(a,b,2),Hc:(a,b,c,d)=>{a=F.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Gc:(a,b)=>zc(a,
b,0),Ec:(a,b,c,d)=>{a=F.getProgramInfoLog(G[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,d,b):0;c&&(u[c>>2]=b)},Fc:(a,b,c)=>{if(c)if(a>=ab)O||=1281;else if(a=G[a],35716==b)a=F.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.xe){var d=F.getProgramParameter(a,35718);for(b=0;b<d;++b)a.xe=Math.max(a.xe,F.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.xe}else if(35722==b){if(!a.ve)for(d=F.getProgramParameter(a,35721),b=0;b<d;++b)a.ve=Math.max(a.ve,F.getActiveAttrib(a,
b).name.length+1);u[c>>2]=a.ve}else if(35381==b){if(!a.we)for(d=F.getProgramParameter(a,35382),b=0;b<d;++b)a.we=Math.max(a.we,F.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.we}else u[c>>2]=F.getProgramParameter(a,b);else O||=1281},ja:Ac,la:Bc,ia:Ac,ka:Bc,na:(a,b,c)=>{c?u[c>>2]=F.ie.getQueryEXT(a,b):O||=1281},Dc:(a,b,c)=>{c?u[c>>2]=F.getRenderbufferParameter(a,b):O||=1281},Ac:(a,b,c,d)=>{a=F.getShaderInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,d,b):0;c&&(u[c>>2]=b)},zc:(a,b,c,
d)=>{a=F.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},yc:(a,b,c,d)=>{if(a=F.getShaderSource(K[a]))b=0<b&&d?A(a,d,b):0,c&&(u[c>>2]=b)},Cc:(a,b,c)=>{c?35716==b?(a=F.getShaderInfoLog(K[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=F.getShaderSource(K[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=F.getShaderParameter(K[a],b):O||=1281},xc:a=>{var b=eb[a];if(!b){switch(a){case 7939:b=Q(Cc().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
F.getParameter(a))||(O||=1280);b=b?Q(b):0;break;case 7938:b=Q(`OpenGL ES 2.0 (${F.getParameter(7938)})`);break;case 35724:b=F.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Q(b);break;default:O||=1280}eb[a]=b}return b},wc:(a,b,c)=>{c?w[c>>2]=F.getTexParameter(a,b):O||=1281},vc:(a,b,c)=>{c?u[c>>2]=F.getTexParameter(a,b):O||=1281},sc:Fc,uc:(a,b,c)=>{Gc(a,b,c,2)},tc:(a,b,c)=>{Gc(a,b,c,0)},
pc:(a,b,c)=>{c?u[c>>2]=F.getVertexAttribOffset(a,b):O||=1281},rc:(a,b,c)=>{Hc(a,b,c,2)},qc:(a,b,c)=>{Hc(a,b,c,5)},oc:(a,b)=>F.hint(a,b),nc:a=>(a=bb[a])?F.isBuffer(a):0,mc:a=>F.isEnabled(a),lc:a=>(a=cb[a])?F.isFramebuffer(a):0,kc:a=>(a=G[a])?F.isProgram(a):0,ra:a=>(a=N[a])?F.ie.isQueryEXT(a):0,jc:a=>(a=H[a])?F.isRenderbuffer(a):0,ic:a=>(a=K[a])?F.isShader(a):0,hc:a=>(a=J[a])?F.isTexture(a):0,ea:a=>(a=db[a])?F.isVertexArray(a):0,fc:a=>F.lineWidth(a),ec:Ic,dc:(a,b)=>{3317==a?fb=b:3314==a&&(gb=b);F.pixelStorei(a,
b)},cb:(a,b)=>{F.sf.polygonModeWEBGL(a,b)},cc:(a,b)=>F.polygonOffset(a,b),eb:(a,b,c)=>{F.jf.polygonOffsetClampEXT(a,b,c)},oa:(a,b)=>{F.ie.queryCounterEXT(N[a],b)},bc:(a,b,c,d,e,f,g)=>{(g=Jc(f,e,c,d,g))?F.readPixels(a,b,c,d,e,f,g):O||=1280},ac:()=>{},$b:(a,b,c,d)=>F.renderbufferStorage(a,b,c,d),_b:(a,b)=>{F.sampleCoverage(a,!!b)},Zb:(a,b,c,d)=>F.scissor(a,b,c,d),Yb:()=>{O||=1280},Xb:Kc,Wb:(a,b,c)=>F.stencilFunc(a,b,c),Vb:(a,b,c,d)=>F.stencilFuncSeparate(a,b,c,d),Ub:a=>F.stencilMask(a),Tb:(a,b)=>F.stencilMaskSeparate(a,
b),Sb:(a,b,c)=>F.stencilOp(a,b,c),Rb:(a,b,c,d)=>F.stencilOpSeparate(a,b,c,d),Qb:(a,b,c,d,e,f,g,l,n)=>{n=n?Jc(l,g,d,e,n):null;F.texImage2D(a,b,c,d,e,f,g,l,n)},Pb:(a,b,c)=>F.texParameterf(a,b,c),Ob:(a,b,c)=>{F.texParameterf(a,b,w[c>>2])},Nb:(a,b,c)=>F.texParameteri(a,b,c),Mb:(a,b,c)=>{F.texParameteri(a,b,u[c>>2])},Lb:(a,b,c,d,e,f,g,l,n)=>{n=n?Jc(l,g,e,f,n):null;F.texSubImage2D(a,b,c,d,e,f,g,l,n)},Kb:Lc,Jb:(a,b,c)=>{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>
2);F.uniform1fv(W(a),d)},Ib:(a,b)=>{F.uniform1i(W(a),b)},Hb:(a,b,c)=>{if(288>=b)for(var d=Mc[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);F.uniform1iv(W(a),d)},Gb:(a,b,c)=>{F.uniform2f(W(a),b,c)},Fb:(a,b,c)=>{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);F.uniform2fv(W(a),d)},Eb:(a,b,c)=>{F.uniform2i(W(a),b,c)},Db:(a,b,c)=>{if(144>=b){b*=2;for(var d=Mc[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=
u.subarray(c>>2,c+8*b>>2);F.uniform2iv(W(a),d)},Cb:(a,b,c,d)=>{F.uniform3f(W(a),b,c,d)},Bb:(a,b,c)=>{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);F.uniform3fv(W(a),d)},Ab:(a,b,c,d)=>{F.uniform3i(W(a),b,c,d)},zb:(a,b,c)=>{if(96>=b){b*=3;for(var d=Mc[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);F.uniform3iv(W(a),d)},yb:(a,b,c,d,e)=>{F.uniform4f(W(a),
b,c,d,e)},xb:(a,b,c)=>{if(72>=b){var d=X[4*b],e=w;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);F.uniform4fv(W(a),d)},wb:(a,b,c,d,e)=>{F.uniform4i(W(a),b,c,d,e)},vb:(a,b,c)=>{if(72>=b){b*=4;for(var d=Mc[b],e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);F.uniform4iv(W(a),d)},ub:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=X[b],f=0;f<b;f+=
4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2]}else e=w.subarray(d>>2,d+16*b>>2);F.uniformMatrix2fv(W(a),!!c,e)},sb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=X[b],f=0;f<b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);F.uniformMatrix3fv(W(a),!!c,e)},rb:Nc,qb:Oc,pb:a=>
{F.validateProgram(G[a])},ob:(a,b)=>F.vertexAttrib1f(a,b),nb:(a,b)=>{F.vertexAttrib1f(a,w[b>>2])},mb:(a,b,c)=>F.vertexAttrib2f(a,b,c),lb:(a,b)=>{F.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},kb:(a,b,c,d)=>F.vertexAttrib3f(a,b,c,d),jb:(a,b)=>{F.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},ib:(a,b,c,d,e)=>F.vertexAttrib4f(a,b,c,d,e),hb:(a,b)=>{F.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Sd:(a,b)=>{F.vertexAttribDivisor(a,b)},gb:Pc,fb:Qc,r:()=>0,va:(a,b,c)=>Rc(a,{Ie:u[c>>2],ze:u[c+4>>2],kf:u[c+
8>>2],ff:b,re:u[c+12>>2],Re:u[c+16>>2]}),S:(a,b)=>{a=U(a);return a?a.requestPointerLock?Ob()?fc(a):b?(Mb(fc,2,[a]),1):-2:-1:-4},Ta:()=>{na("OOM")},d:a=>{eval(a?z(r,a):"")},X:Sc,x:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Tc(a,b),J:(a,b,c,d)=>Uc(a,b,c,d,12,"blur"),k:Xb,o:(a,b,c)=>{a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},K:(a,b,c,d)=>Uc(a,b,c,d,13,"focus"),z:(a,b,c,d)=>{if(!S.fullscreenEnabled())return-1;a=U(a);if(!a)return-4;Vc(a,b,c,d,"webkitfullscreenchange");
return Vc(a,b,c,d,"fullscreenchange")},V:(a,b,c)=>Sc()?-1:Wc(a,b,c,26,"gamepadconnected"),U:(a,b,c)=>Sc()?-1:Wc(a,b,c,27,"gamepaddisconnected"),C:(a,b,c,d)=>Xc(a,b,c,d,2,"keydown"),A:(a,b,c,d)=>Xc(a,b,c,d,1,"keypress"),B:(a,b,c,d)=>Xc(a,b,c,d,3,"keyup"),Sa:(a,b,c)=>{a=V(a);Fb(a,b,c)},P:(a,b,c,d)=>Zc(a,b,c,d,5,"mousedown"),N:(a,b,c,d)=>Zc(a,b,c,d,33,"mouseenter"),M:(a,b,c,d)=>Zc(a,b,c,d,34,"mouseleave"),Q:(a,b,c,d)=>Zc(a,b,c,d,8,"mousemove"),O:(a,b,c,d)=>Zc(a,b,c,d,6,"mouseup"),D:(a,b,c,d)=>{if(!document||
!document.body||!(document.body.requestPointerLock||document.body.oe||document.body.Se||document.body.Qe))return-1;a=U(a);if(!a)return-4;$c(a,b,c,d,"mozpointerlockchange");$c(a,b,c,d,"webkitpointerlockchange");$c(a,b,c,d,"mspointerlockchange");return $c(a,b,c,d,"pointerlockchange")},s:(a,b,c,d)=>ad(a,b,c,d),E:(a,b,c,d)=>bd(a,b,c,d,25,"touchcancel"),G:(a,b,c,d)=>bd(a,b,c,d,23,"touchend"),F:(a,b,c,d)=>bd(a,b,c,d,24,"touchmove"),I:(a,b,c,d)=>bd(a,b,c,d,22,"touchstart"),y:(a,b,c)=>cd(a,b,c),L:(a,b,c,
d)=>(a=U(a))?"undefined"!=typeof a.onwheel?dd(a,b,c,d):-1:-4,wa:a=>document.title=a?z(r,a):"",q:()=>{throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Za:(a,b)=>{var c=0,d=0,e;for(e of pd()){var f=b+c;v[a+d>>2]=f;c+=A(e,f,Infinity)+1;d+=4}return 0},_a:(a,b)=>{var c=pd();v[a>>2]=c.length;a=0;for(var d of c)a+=pb(d)+1;v[b>>2]=a;return 0},Z:()=>52,$a:()=>52,Ya:function(){return 70},_:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=v[b>>2],
l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var t=a,B=r[g+n],L=qd[t];0===B||10===B?((1===t?fa:k)(z(L)),L.length=0):L.push(B)}e+=l}v[d>>2]=e;return 0},ba:ic,a:jc,Va:kc,b:lc,u:mc,n:nc,w:oc,ma:pc,R:qc,tb:rc,p:tc,t:uc,i:vc,c:wc,v:yc,l:Fc,Jd:Ic,H:Kc,f:Lc,h:Nc,ed:Oc,j:Pc,Bc:Qc},Z;
(async function(){function a(c){Z=c.exports;ha=Z.Ud;c=ha.buffer;q=new Int8Array(c);ja=new Int16Array(c);r=new Uint8Array(c);ka=new Uint16Array(c);u=new Int32Array(c);v=new Uint32Array(c);w=new Float32Array(c);x=new Float64Array(c);la=new BigInt64Array(c);new BigUint64Array(c);ac=Z.Xd;y--;h.monitorRunDependencies?.(y);0==y&&ma&&(c=ma,ma=null,c());return Z}y++;h.monitorRunDependencies?.(y);var b={a:xd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});oa??=h.locateFile?
h.locateFile("index.wasm",da):da+"index.wasm";return a((await ra(b)).instance)})();var yd=h._main=(a,b)=>(yd=h._main=Z.Wd)(a,b),P=a=>(P=Z.Yd)(a),Vb=a=>(Vb=Z.Zd)(a),Sb=a=>(Sb=Z._d)(a),Ub=()=>(Ub=Z.$d)();function zd(a=[]){var b=yd;a.unshift(ba);var c=a.length,d=Sb(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=Tb(g);e+=4});v[e>>2]=0;try{var f=b(c,d);Ea(f)}catch(g){Ca(g)}}
function Ad(a=aa){function b(){h.calledRun=!0;if(!p){Z.Vd();h.onRuntimeInitialized?.();h.noInitialRun||zd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ua.push(c)}ta(ua)}}if(0<y)ma=Ad;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)wa();ta(va);0<y?ma=Ad:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();Ad();
